"""removed unique constraint

Revision ID: 09f4b7465b6d
Revises: fb88855c9727
Create Date: 2025-04-26 22:13:53.124445

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09f4b7465b6d'
down_revision = 'fb88855c9727'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_constraint('unique_name', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique_name', ['text'])

    # ### end Alembic commands ###
