"""added type column

Revision ID: 43725e5db507
Revises: 66b4a2a02878
Create Date: 2025-04-26 20:35:51.142206

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43725e5db507'
down_revision = '66b4a2a02878'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.String(length=20), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_column('type')

    # ### end Alembic commands ###
