"""added ticker column

Revision ID: 66b4a2a02878
Revises: e226deb413c7
Create Date: 2025-04-19 22:23:14.303115

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66b4a2a02878'
down_revision = 'e226deb413c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ticker', sa.String(length=6), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_column('ticker')

    # ### end Alembic commands ###
