"""added unique constraint for post name and ticker

Revision ID: e0d1aac3c61c
Revises: 09f4b7465b6d
Create Date: 2025-04-26 22:25:48.644875

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0d1aac3c61c'
down_revision = '09f4b7465b6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('text_hash', sa.String(length=64), nullable=False))
        batch_op.create_unique_constraint('unique_ticker_texthash', ['ticker', 'text_hash'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_constraint('unique_ticker_texthash', type_='unique')
        batch_op.drop_column('text_hash')

    # ### end Alembic commands ###
