"""added unique constraint for post name

Revision ID: fb88855c9727
Revises: 43725e5db507
Create Date: 2025-04-26 22:08:35.727456

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb88855c9727'
down_revision = '43725e5db507'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique_name', ['text'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_constraint('unique_name', type_='unique')

    # ### end Alembic commands ###
